# Each top-level key is a column name in the pre-processed DataFrame.
# The level is a list of dictionaries with the keys 'method' and 'args' that call the specified comparison method with the specified arguments.
first_name:
    - method: compare_exact 
      args: 
           n_chars: 
    - method: compare_exact 
      args:
           n_chars: 5
    - method: compare_exact 
      args:
           n_chars: -5
    - method: compare_exact 
      args:
           n_chars: 3
    - method: compare_exact 
      args:
           n_chars: -3
    - method: compare_string_distance
      args:
           method: jarowinkler
middle_name:
    - method: compare_exact 
      args:
           n_chars: 
    - method: compare_exact 
      args:
           n_chars: 5
    - method: compare_exact 
      args:
           n_chars: -5
    - method: compare_exact 
      args:
           n_chars: 3
    - method: compare_exact 
      args:
           n_chars: -3
    - method: compare_string_distance
      args:
           method: jarowinkler
last_name:
    - method: compare_exact 
      args:
           n_chars: 
    - method: compare_exact 
      args:
           n_chars: 5
    - method: compare_exact 
      args:
           n_chars: -5
    - method: compare_exact 
      args:
           n_chars: 3
    - method: compare_exact 
      args:
           n_chars: -3
    - method: compare_string_distance
      args:
           method: jarowinkler
dob:
    - method: compare_exact
      args:
           n_chars: 
    - method: compare_exact
      args:
           n_chars: 4
    - method: compare_swap_month_days
      args:
           swap_score: .5
ssn:
    - method: compare_exact
      args:
           n_chars: 
    - method: compare_exact
      args:
           n_chars: -4
    - method: compare_string_distance
      args:
           method: jaro
dmv_number:
    - method: compare_exact
      args:
           n_chars: 
    - method: compare_string_distance
      args:
           method: jaro
race:
    - method: compare_list
      args:
            method: any
    - method: compare_list
      args:
           method: all
ethnicity:
    - method: compare_exact
      args:
           n_chars: 
sex:
    - method: compare_exact
      args:
           n_chars: 
    - method: compare_exact
      args:
           n_chars: -1

