version: '3'

services:
    webapp:
        container_name: webapp
        build: ./webapp
        volumes:
            - ./webapp/tmp:/csh/webapp/tmp
        ports:
            - 5000:5000
        env_file:
            - webapp.env
            - .env

    matcher_worker:
        build: ./matcher
        container_name: matcher_worker
        command: python manage.py
        depends_on:
            - redis
        env_file:
            - matcher.env
            - .env

    webapp_worker:
        image: matchingtool_webapp
        container_name: webapp_worker
        command: python manage.py runworker
        volumes:
            - ./webapp/tmp:/csh/webapp/tmp
        depends_on:
            - redis
            - webapp
        env_file:
            - webapp.env
            - .env

    redis:
       image: redis
       container_name: csh_queue
       ports:
         - 6379:6379

    nginx:
        image: "nginx:1.13.5"
        ports:
            - 80:80
        volumes:
            - ./webapp/conf.d:/etc/nginx/conf.d
        depends_on: 
            - webapp
