site_name: Matching Tool
docs_dir: sources
theme: material
pages:
    - {Home: index.md}
    - For Users:
        - {Using the Tool: users/using.md}
        - {Schemas: users/schemas.md}
    - For Administrators:
        - {Installing: admin/install.md}
        - {Troubleshooting: admin/troubleshooting.md}
        - {Updating: admin/updating.md}
    - For Developers:
        - {Creating a new Schema: dev/schemas.md}
        - {Modifying the Webapp: dev/webapp.md}
        - {Modifying the Matching Service : dev/matching.md}
